name: server
description: A web server built using the shelf package.
version: 0.0.1
#homepage: https://www.example.com
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.1 <3.0.0'

dependencies:
  jaguar: ^2.4.26
  jaguar_auth: ^2.4.4
  jaguar_mongo:
  jaguar_serializer: ^2.2.9
  mongo_dart:
  jaguar_reflect: ^2.4.5
  jaguar_dev_proxy:
  common:
    path: ../common
  jaguar_eventsource:
  simple_pubsub:
  jaguar_settings: ^4.0.1

dev_dependencies:
  jaguar_serializer_cli:
  build_runner: