name: server
description: A web server built using the shelf package.
version: 0.0.1
#homepage: https://www.example.com
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.1 <3.0.0'

dependencies:
  jaguar: ^2.4.12
  jaguar_auth: ^2.4.0
  jaguar_mongo:
  jaguar_serializer:
  mongo_dart:
  jaguar_reflect: ^2.4.0
  jaguar_dev_proxy:
  common:
    path: ../common