name: server
description: A web server built using the shelf package.
version: 0.0.1
#homepage: https://www.example.com
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.1 <3.0.0'

dependencies:
  jaguar: ^2.4.33
  jaguar_auth: ^2.4.4
  jaguar_mongo:
  jaguar_serializer: ^2.2.9
  mongo_dart:
  jaguar_reflect: ^2.4.6
  jaguar_dev_proxy:
  jaguar_eventsource: ^1.0.6
  simple_pubsub: ^1.0.0
  jaguar_settings: ^4.0.1
  short_readable_id: ^1.5.1
  common:
    path: ../common
  conn_pool: ^2.1.9
  open_weather_api: ^1.5.5

dev_dependencies:
  jaguar_serializer_cli:
  build_runner: