version: '3.5'
services:
  echannel:
    image: echannel
    depends_on:
      - mongo
    expose:
      - 80
    ports:
      - "127.0.0.1:9000:80"
    restart: always
    secrets:
      - echannel_config
    volumes:
      - type: bind
        source: ./media
        target: /var/local/echannel/media
  web:
    image: echannel_web
    expose:
      - 80
    ports:
      - "127.0.0.1:9005:80"
    restart: always
  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - data:/data/db
    restart: always
  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    restart: always
    depends_on:
      - echannel
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - type: bind
        source: ./media
        target: /var/local/echannel/media
    secrets:
      - ssl_cert.crt
      - ssl_key.pem
volumes:
  data:
secrets:
  echannel_config:
    file: echannel_config.yaml
  ssl_cert.crt:
    file: ssl_cert.crt
  ssl_key.pem:
    file: ssl_key.pem